export const machinesArray = [
  ['Extruder', 'OK'],
  ['Extruder', 'OK'],
  ['Extruder', 'Kritisch'],
  ['Extruder', 'Kritisch'],
  ['Extruder', 'Kritisch'],
  ['Extruder', 'OK'],
  ['Extruder', 'OK'],
  ['Extruder', 'OK'],
  ['Extruder', 'OK'],
  ['Extruder', 'NA'],
  ['Extruder', 'OK'],
  ['Extruder', 'OK'],
  ['Extruder', 'Kritisch'],
  ['Extruder', 'OK'],
  ['Extruder', 'NA'],
  ['Extruder', 'NA'],
  ['Extruder', 'OK'],
  ['Extruder', 'OK'],
  ['Extruder', 'OK'],
  ['Extruder', 'OK'],
  ['Extruder', 'OK'],
  ['Extruder', 'OK'],
  ['Extruder', 'NA'],
  ['Extruder', 'Kritisch'],
];
